### ISSUE TITLE
More getting started docs

### ISSUE THREAD

**Issue by QHose** [tozd/docker-meteor#2]
hi, 

A small chapter with the docker commands you have to type in would be great. 

For example what is unclear for me is this. I understand what a mongo_url is, and if I order one at compose I get an URL to a specific database. But if I run a mongo image, I have no pointer to a default database, and I don't see a 'use database' command in the docker files.

**Comment by mitar** [comment]
There are examples for every environment variable. If you use a [Mongo image](https://github.com/tozd/docker-meteor-mongodb), then the question is how you expose its IP to the Meteor container. You can link containers, or use host resolving. But if you provide IP at `mongodb` name, then the examples in README should work for you.

**Comment by QHose** [comment]
hi mitar, I understand the container linking, and I will checkout the docs you suggested, looks good! There are off small things to connect :)

So the question I always had was (like I ask above); its very easy to connect to an online mongo database, you just get the URL and it works. But I miss a little thing
* does meteor create a new database?
* can I just connect to mongo:host:port/
* or do I need to create a db and user first

**Comment by mitar** [comment]
> does meteor create a new database?

In default MongoDB installation there are no permissions and anyone can simply create a database. Database in MongoDB is created simply by starting using it. For example, if you use o[fficial MongoDB Docker image](https://hub.docker.com/_/mongo/), this is how it is.

For Meteor, it is a bit trickier, becasue for the us of oplog, you have to create a replica set. This is why there is a [tozd/meteor-mongodb](https://github.com/tozd/docker-meteor-mongodb) image which has an init script for the database which creates a database  for both. And I dislike that there is no authentication, even if it is all running on one machine, so it creates also necessary users. All that is controlled by `MONGODB_ADMIN_PWD`, `MONGODB_CREATE_PWD`, and `MONGODB_OPLOGGER_PWD` environment variables. [See here how it works internaly](https://github.com/tozd/docker-meteor-mongodb/blob/master/etc-2.6/service/mongod/run.initialization).

So now the interesting thing is that you can create one `run.config` file n the host and then mount it into both Meteor and Meteor MongoDB Docker containers. To configure it. The first will know how to connect to the database. And the second will know how to initialize the database. Also, the first [makes sure that database is up](https://github.com/tozd/docker-meteor/blob/master/etc/service/meteor/wait_db.js) before running Meteor.

By using a file which you mount, no password are provided in Docker environment variables, because that can also leak information to anyone who has access to Docker API on your host. (I dislike passwords being available through `docker inspect`).

> can I just connect to mongo:host:port/

Mostly yes, but see above that sometimes you want/need to specify authentication.

> or do I need to create a db and user first

For Meteor you need replica set, so you can do this by setting environment variables.

So, there are various ways to do this. You can simply configure Docker environment variables, or you can create a file which you then volume mount in.

**Comment by mitar** [comment]
I hoped that all that was clear from instructions, but if not, feel free to open PRs to improve the situation. :-)

**Comment by QHose** [comment]
thanks! Cool, yeah I am creating docs on the fly, and will share this later on with the community. Do you already have a docker-compose file? That would be super easy, if I can just copy paste your code into my compose file 

```
version: "3.3"
services:
  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        networks:
        - saasdemo
  qrs:
    image: qrsmeteor:1.0.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
        - MONGO_URL='mongodb://mongodb:27017/test' 
        - PORT=3000 
        - ROOT_URL='http://localhost'
    volumes:
        - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
    # configs:
    #   - my_config
    #   - my_other_config
    ports:
    -  "80:3000"
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - saasdemo
networks:
  saasdemo:
```

**Comment by QHose** [comment]
So for non docker users (or people that have watched videos and docs)

- install docker
- clone github (if needed)
- bash run.sh
- change run.config

I spend the last hour figuring out what to do...  and I guess it must be very simple, and I think your image does all the heavy lifting like creating a database and users...

**Comment by mitar** [comment]
So it seems one thing to add to documentation is that you should mount that configuration as **file volume**. :-)

**Comment by QHose** [comment]
Yeah, so what we should add is


·       You can run the default mongo image

·       Mongo_url:yourMongoDNSName (no path)

Or use the tozd image

Do  x y z


The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by joshuacox** [comment]
maybe add a docker-compose.yml as well for easy demo?

**Comment by imcoddy** [comment]
I also find this document is not clear for non-docker users, a bit confused now and really looking forward to see a docker-compose file so user only need to run ```docker-compose up```

I have created one as follow, it seems running but I have no clue how I can open the browser and see it run

```
dashboard:
  image: tozd/meteor
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=
   - ROOT_URL=
   - MAIL_URL=

mongo:
  image: tozd/meteor-mongodb:3.4
```

Can anyone help me enhance the above?
